### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by logros** [jbehuet/mattermost-google-calendar-notification#1]
Please help with installation of script.
my system centos 7, mattermost 4.5
I clone repo.
install nodejs, npm via yum.
cd to folder with script and run npm i, it finished with errors:
npm WARN mattermost-google-calendar-notification@1.0.0 No repository field.

when do next command npm start i got errors like below:
npm ERR! Linux 3.10.0-693.11.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/mattermost-google-calendar-notification/npm-debug.log
-------------------------------------------
Log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.12.2
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules.bundled/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules.bundled/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules.bundled/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules.bundled/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules.bundled/read-package-json/read-json.js:311:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules.bundled/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:457:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:444:12)
5 verbose cwd /tmp/mattermost-google-calendar-notification
6 error Linux 3.10.0-693.11.1.el7.x86_64
7 error argv "/usr/bin/node" "/usr/bin/npm" "start"
8 error node v6.12.2
9 error npm  v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

Can you help with integarate please.

**Comment by jbehuet** [comment]
Hey,

I've fixed this issue in last commit https://github.com/jbehuet/mattermost-google-calendar-notification/commit/5e82e597e798b90b95c3a75a33ffccca408d0ffa with adding missing script.
